name: deploy-frontend-to-stage
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  deploy-to-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Check for version change
        id: version_change
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: hello-world
        run: echo "Hello World"
